### PR TITLE
Styled the filters and event Cards page

### PR DESCRIPTION
**Pull request by Abdalla2024**

### CODE REVIEW

**Review by Romerico234 — COMMENTED** [review]
Screenshot 2024-12-02 at 4 00 39 PM

Perks is getting caught off. But, I kinda doubt that these descriptions will be that long where you'll really have to worry about this issue. Pull from dev.

**Review by Romerico234 — DISMISSED** [review]
Screenshot 2024-12-02 at 4 02 07 PM

Title is getting cut off

**Comment by Abdalla2024** [comment]
I had the title limit at two lines so if there is a really long title, it doesn't take up too much of the screen. They can see the title in the image or just read the description. Also the description is scrollable if it is long enough, but I just need to pull from dev to get the perks

**Comment by curlyLasagna** [comment]
> Screenshot 2024-12-02 at 4 02 07 PM
> 
> Title is getting cut off

Let's just create another PR for a click to expand

**Pull request merged**
